=== fwiep/trekisode/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://github.com/fwiep/trekisode" xmlns:t="https://github.com/fwiep/trekisode" elementFormDefault="qualified">

  <xs:element name="StarTrek" type="t:TypeStarTrek">
    <xs:unique name="uniqueSeries">
      <xs:selector xpath="t:Series" />
      <xs:field xpath="@code" />
    </xs:unique>
  </xs:element>

  <xs:complexType name="TypeStarTrek">
    <xs:sequence>
      <xs:element maxOccurs="12" minOccurs="12" name="Series" type="t:TypeSeries">
        <xs:unique name="uniqueSeasonNumber">
          <xs:selector xpath="t:Season" />
          <xs:field xpath="@number" />
        </xs:unique>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="TypeSeries">
    <xs:sequence>
      <xs:element maxOccurs="7" minOccurs="1" name="Season" type="t:TypeSeason">
        <xs:unique name="uniqueEpisodeNumber">
          <xs:selector xpath="t:Episode" />
          <xs:field xpath="@number" />
        </xs:unique>
      </xs:element>
    </xs:sequence>

    <xs:attribute name="code" type="t:SeriesCode" use="required" />
    <xs:attribute name="name" type="t:StringNonEmpty" use="required" />
  </xs:complexType>

  <xs:complexType name="TypeSeason">
    <xs:sequence>
      <xs:element maxOccurs="30" minOccurs="0" name="Episode" type="t:TypeEpisode"></xs:element>
    </xs:sequence>
    <xs:attribute name="number" type="t:SeasonNumber" use="required" />
  </xs:complexType>

  <xs:complexType name="TypeEpisode">
    <xs:attribute name="number" type="t:EpisodeNumber" use="required" />
    <xs:attribute name="airdate" type="t:DateEmpty" use="required" />
    <xs:attribute name="name" type="t:StringNonEmpty" use="required" />
  </xs:complexType>

  <xs:simpleType name="StringNonEmpty">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="DateEmpty">
    <xs:union memberTypes="t:Empty xs:date" />
  </xs:simpleType>

  <xs:simpleType name="EpisodeNumber">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0" />
      <xs:maxInclusive value="30" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SeasonNumber">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1" />
      <xs:maxInclusive value="7" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="SeriesCode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="TOS" />
      <xs:enumeration value="TAS" />
      <xs:enumeration value="TNG" />
      <xs:enumeration value="DS9" />
      <xs:enumeration value="VOY" />
      <xs:enumeration value="ENT" />
      <xs:enumeration value="DIS" />
      <xs:enumeration value="ST" />
      <xs:enumeration value="PIC" />
      <xs:enumeration value="LD" />
      <xs:enumeration value="PRO" />
      <xs:enumeration value="SNW" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Empty">
    <xs:restriction base="xs:string">
      <xs:enumeration value="" />
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== fwiep/trekisode/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<StarTrek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" xmlns="">
  <Series code="TOS" name="The Original Series">
    <Season number="1">
      <Episode number="0" airdate="1988-10-04" name="The Cage" />
      <Episode number="1" airdate="1966-09-22" name="Where No Man Has Gone Before" />
      <Episode number="2" airdate="1966-11-10" name="The Corbomite Maneuver" />
      <Episode number="3" airdate="1966-10-13" name="Mudd's Women" />
      <Episode number="4" airdate="1966-10-06" name="The Enemy Within" />
      <Episode number="5" airdate="1966-09-08" name="The Man Trap" />
      <Episode number="6" airdate="1966-09-29" name="The Naked Time" />
      <Episode number="7" airdate="1966-09-15" name="Charlie X" />
      <Episode number="8" airdate="1966-12-13" name="Balance of Terror" />
      <Episode number="9" airdate="1966-10-20" name="What Are Little Girls Made Of?" />
      <Episode number="10" airdate="1966-11-03" name="Dagger of the Mind" />
      <Episode number="11" airdate="1966-10-27" name="Miri" />
      <Episode number="12" airdate="1966-12-08" name="The Conscience of the King" />
      <Episode number="13" airdate="1967-01-05" name="The Galileo Seven" />
      <Episode number="14" airdate="1967-02-02" name="Court Martial" />
      <Episode number="15" airdate="1966-11-17" name="The Menagerie, Part I" />
      <Episode number="16" airdate="1966-11-24" name="The Menagerie, Part II" />
      <Episode number="17" airdate="1966-12-29" name="Shore Leave" />
      <Episode number="18" airdate="1967-01-12" name="The Squire of Gothos" />
      <Episode number="19" airdate="1967-01-19" name="Arena" />
      <Episode number="20" airdate="1967-03-30" name="The Alternative Factor" />
      <Episode number="21" airdate="1967-01-26" name="Tomorrow is Yesterday" />
      <Episode number="22" airdate="1967-02-09" name="The Return of the Archons" />
      <Episode number="23" airdate="1967-02-23" name="A Taste of Armageddon" />
      <Episode number="24" airdate="1967-02-16" name="Space Seed" />
      <Episode number="25" airdate="1967-03-02" name="This Side of Paradise" />
      <Episode number="26" airdate="1967-03-09" name="The Devil in the Dark" />
      <Episode number="27" airdate="1967-03-23" name="Errand of Mercy" />
      <Episode number="28" airdate="1967-04-06" name="The City on the Edge of Forever" />
      <Episode number="29" airdate="1967-04-13" name="Operation -- Annihilate!" />
    </Season>
    <Season number="2">
      <Episode number="1" airdate="1967-10-27" name="Catspaw" />
      <Episode number="2" airdate="1967-11-10" name="Metamorphosis" />
      <Episode number="3" airdate="1967-12-01" name="Friday's Child" />
      <Episode number="4" airdate="1967-09-22" name="Who Mourns for Adonais?" />
      <Episode number="5" airdate="1967-09-15" name="Amok Time" />
      <Episode number="6" airdate="1967-10-20" name="The Doomsday Machine" />
      <Episode number="7" airdate="1967-12-22" name="Wolf in the Fold" />
      <Episode number="8" airdate="1967-09-29" name="The Changeling" />
      <Episode number="9" airdate="1967-10-13" name="The Apple" />
      <Episode number="10" airdate="1967-10-06" name="Mirror, Mirror" />
      <Episode number="11" airdate="1967-12-08" name="The Deadly Years" />
      <Episode number="12" airdate="1967-11-03" name="I, Mudd" />
      <Episode number="13" airdate="1967-12-29" name="The Trouble with Tribbles" />
      <Episode number="14" airdate="1968-03-15" name="Bread and Circuses" />
      <Episode number="15" airdate="1967-11-17" name="Journey to Babel" />
      <Episode number="16" airdate="1968-02-02" name="A Private Little War" />
      <Episode number="17" airdate="1968-01-05" name="The Gamesters of Triskelion" />
      <Episode number="18" airdate="1967-12-15" name="Obsession" />
      <Episode number="19" airdate="1968-01-19" name="The Immunity Syndrome" />
      <Episode number="20" airdate="1968-01-12" name="A Piece of the Action" />
      <Episode number="21" airdate="1968-02-23" name="By Any Other Name" />
      <Episode number="22" airdate="1968-02-09" name="Return to Tomorrow" />
      <Episode number="23" airdate="1968-02-16" name="Patterns of Force" />
      <Episode number="24" airdate="1968-03-08" name="The Ultimate Computer" />
      <Episode number="25" airdate="1968-03-01" name="The Omega Glory" />
      <Episode number="26" airdate="1968-03-29" name="Assignment: Earth" />
    </Season>
    <Season number="3">
      <Episode number="1" airdate="1968-10-25" name="Spectre of the Gun" />
      <Episode number="2" airdate="1968-12-20" name="Elaan of Troyius" />
      <Episode number="3" airdate="1968-10-04" name="The Paradise Syndrome" />
      <Episode number="4" airdate="1968-09-27" name="The Enterprise Incident" />
      <Episode number="5" airdate="1968-10-11" name="And the Children Shall Lead" />
      <Episode number="6" airdate="1968-09-20" name="Spock's Brain" />
      <Episode number="7" airdate="1968-10-18" name="Is There in Truth No Beauty?" />
      <Episode number="8" airdate="1968-12-06" name="The Empath" />
      <Episode number="9" airdate="1968-11-15" name="The Tholian Web" />
      <Episode number="10" airdate="1968-11-08" name="For the World is Hollow and I Have Touched the Sky" />
      <Episode number="11" airdate="1968-11-01" name="Day of the Dove" />
      <Episode number="12" airdate="1968-11-22" name="Plato's Stepchildren" />
      <Episode number="13" airdate="1968-11-29" name="Wink of an Eye" />
      <Episode number="14" airdate="1969-01-24" name="That Which Survives" />
      <Episode number="15" airdate="1969-01-10" name="Let That Be Your Last Battlefield" />
      <Episode number="16" airdate="1969-01-03" name="Whom Gods Destroy" />
      <Episode number="17" airdate="1969-01-17" name="The Mark of Gideon" />
      <Episode number="18" airdate="1969-01-31" name="The Lights of Zetar" />
      <Episode number="19" airdate="1969-02-28" name="The Cloud Minders" />
      <Episode number="20" airdate="1969-02-21" name="The Way to Eden" />
      <Episode number="21" airdate="1969-02-14" name="Requiem for Methuselah" />
      <Episode number="22" airdate="1969-03-07" name="The Savage Curtain" />
      <Episode number="23" airdate="1969-03-14" name="All Our Yesterdays" />
      <Episode number="24" airdate="1969-06-03" name="Turnabout Intruder" />
    </Season>
  </Series>
  <Series code="TAS" name="The Animated Series">
    <Season number="1">
      <Episode number="1" airdate="1973-09-08" name="Beyond the Farthest Star" />
      <Episode number="2" airdate="1973-09-15" name="Yesteryear" />
      <Episode number="3" airdate="1973-09-22" name="One of Our Planets Is Missing" />
      <Episode number="4" airdate="1973-09-29" name="The Lorelei Signal" />
      <Episode number="5" airdate="1973-10-06" name="More Tribbles, More Troubles" />
      <Episode number="6" airdate="1973-10-13" name="The Survivor" />
      <Episode number="7" airdate="1973-10-20" name="The Infinite Vulcan" />
      <Episode number="8" airdate="1973-10-27" name="The Magicks of Megas-Tu" />
      <Episode number="9" airdate="1973-11-03" name="Once Upon a Planet" />
      <Episode number="10" airdate="1973-11-10" name="Mudd's Passion" />
      <Episode number="11" airdate="1973-11-17" name="The Terratin Incident" />
      <Episode number="12" airdate="1973-11-24" name="The Time Trap" />
      <Episode number="13" airdate="1973-12-01" name="The Ambergris Element" />
      <Episode number="14" airdate="1973-12-15" name="The Slaver Weapon" />
      <Episode number="15" airdate="1974-01-05" name="The Eye of the Beholder" />
      <Episode number="16" airdate="1974-01-12" name="The Jihad" />
    </Season>
    <Season number="2">
      <Episode number="1" airdate="1974-09-07" name="The Pirates of Orion" />
      <Episode number="2" airdate="1974-09-14" name="Bem" />
      <Episode number="3" airdate="1974-09-21" name="The Practical Joker" />
      <Episode number="4" airdate="1974-09-28" name="Albatross" />
      <Episode number="5" airdate="1974-10-05" name="How Sharper Than a Serpent's Tooth" />
      <Episode number="6" airdate="1974-10-12" name="The Counter-Clock Incident" />
    </Season>
  </Series>
  <Series code="TNG" name="The Next Generation">
    <Season number="1">
      <Episode number="1" airdate="1987-09-28" name="Encounter at Farpoint, Part I" />
      <Episode number="2" airdate="1987-09-28" name="Encounter at Farpoint, Part II" />
      <Episode number="3" airdate="1987-10-05" name="The Naked Now" />
      <Episode number="4" airdate="1987-10-12" name="Code of Honor" />
      <Episode number="5" airdate="1987-10-19" name="The Last Outpost" />
      <Episode number="6" airdate="1987-10-26" name="Where No One Has Gone Before" />
      <Episode number="7" airdate="1987-11-02" name="Lonely Among Us" />
      <Episode number="8" airdate="1987-11-09" name="Justice" />
      <Episode number="9" airdate="1987-11-16" name="The Battle" />
      <Episode number="10" airdate="1987-11-23" name="Hide and Q" />
      <Episode number="11" airdate="1987-11-30" name="Haven" />
      <Episode number="12" airdate="1988-01-11" name="The Big Goodbye" />
      <Episode number="13" airdate="1988-01-18" name="Datalore" />
      <Episode number="14" airdate="1988-01-25" name="Angel One" />
      <Episode number="15" airdate="1988-02-01" name="11001001" />
      <Episode number="16" airdate="1988-02-08" name="Too Short a Season" />
      <Episode number="17" airdate="1988-02-15" name="When The Bough Breaks" />
      <Episode number="18" airdate="1988-02-22" name="Home Soil" />
      <Episode number="19" airdate="1988-03-14" name="Coming of Age" />
      <Episode number="20" airdate="1988-03-21" name="Heart of Glory" />
      <Episode number="21" airdate="1988-04-11" name="The Arsenal of Freedom" />
      <Episode number="22" airdate="1988-04-18" name="Symbiosis" />
